title: Scratch Addons Suggestions
description: Suggestions for Scratch Addons taken from the old community Discord server
baseurl: "/suggestions"
url: "https://scratchaddons-community.github.io"
twitter_username: scratchaddons
github_username: scratchaddons-community

plugins:
    - jekyll-paginate-v2

collections:
    suggestions:
        output: true
        permalink: /:name

defaults:
    - scope:
          path: ""
          type: "suggestions"
      values:
          layout: "suggestion"
    - scope:
          path: "author"
      values:
          layout: "author"
    - scope:
          path: ""
      values:
          layout: "default"

pagination:
    enabled: true
