name: Deploy Jekyll site to Pages
on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    id-token: write
    pages: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Setup Ruby
              uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
              with:
                  bundler-cache: true

            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

            - name: Build
              run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
              env:
                  JEKYLL_ENV: production

            - name: Upload
              uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-24.04
        needs: build
        steps:
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
