name: Deploy Jekyll site to Pages
on:
    push:
        branches: main
    workflow_dispatch:

permissions:
    contents: read

concurrency:
    group: ${{github.workflow}}-${{github.ref}}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Setup Ruby
              uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
              with:
                  bundler-cache: true

            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

            - name: Build
              run: bundle exec jekyll build --baseurl "$base_path"
              env:
                  JEKYLL_ENV: production
                  base_path: ${{steps.pages.outputs.base_path}}

            - name: Upload
              uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0

    deploy:
        needs: build
        runs-on: ubuntu-24.04

        environment:
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}

        permissions:
            id-token: write # Needed for actions/deploy-pages
            pages: write # Needed to deploy to Pages

        steps:
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
